services:
  user_db:
    image: postgres:alpine
    container_name: users_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
volumes:
  user_data: