services:
  course_db:
    image: postgres:alpine
    container_name: courses_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - course_data:/var/lib/postgresql/data
volumes:
  course_data: